A MR
roynatech2544/android_device_samsung_a20-a20e pull request #16
Opened 2024-04-12 19:57 UTC by EliasTheGrandMasterOfMistakes

2024-04-16 10:18 UTC, roynatech2544 requested changes
Just remove those new props (they won't do anything) and I'll be happy to merge others

2024-04-16 16:34 UTC, EliasTheGrandMasterOfMistakes commented
> Just remove those new props commit (they won't do anything), and I'll be happy to merge other commits

thanks, fixed now

2024-04-17 10:07 UTC, roynatech2544 requested changes
I mean remove 70a6efdd907c1cbce6b8ea12fdf8d72c2361fb18`

2024-04-17 22:39 UTC, EliasTheGrandMasterOfMistakes commented
> I mean remove [70a6efd](https://github.com/eurekadevelopment/android_device_samsung_exynos7885/commit/70a6efdd907c1cbce6b8ea12fdf8d72c2361fb18)`

oh sorry for my confusion

2024-04-19 15:27 UTC, roynatech2544 approved these changes

2024-04-19 15:27 UTC, merged